language: python
python:
  - "3.5"

cache: pip

services:
  - redis-server

addons:
  postgresql: "9.4"

install:
  - pip install -r requirements.txt --quiet
  - pip install codecov

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate
  - python manage.py test
  - coverage run --source=password manage.py test password

after_success:
  - codecov