language: python

python:
  - 3.4

#services: postgresql
addons:
  postgresql: "9.3"

before_install:
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt --quiet

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate --noinput
  - python manage.py migrate --database=backup